name: Maven Build

on:
  workflow_dispatch:

jobs:
  maven-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: create file
      run: echo "hello" >> file.txt
  
    - name: "Upload build artifacts: artifacts"
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: ./file.txt
        retention-days: 3

