name: CT1
on:
  workflow_call:
    inputs: {}
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |- 
          if [ "something" == true ]]; then 
            echo "triue"
          else 
            echo "false"
          fi
        shell: sh
      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: false
    - name: upload
        uses: actions/upload-artifact@v4
      name: Build