name: my2
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Build
        run: dotnet build MyDotNetApp.csproj
      - name: Test
        run: dotnet test MyDotNetApp.Tests.csproj
