name: dynamic-wf
on:
  workflow_dispatch: null
  push:
    branches:
      - main
      - develop
      - feat/**
jobs:
  call-am-generic-build2:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        uses: actions/upload-artifact@v4
        with:
          param-1: ''
    uses: turbo5000c/am-reuseable-workflow/.github/workflows/am-generic-build2.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
