name: standard-pipeline
on:
  workflow_dispatch: null
  push:
    branches:
      - feat/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          echo 'Building the project...'
          npm install
          npm run build
        shell: bash
      - name: Test
        run: |
          echo 'Running tests...'
          npm test
      - name: Code Quality
        run: |
          echo 'Checking code quality...'
          npm run lint
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Security Scanning
        uses: github/codeql-action/codeql-analysis@v2
        with:
          languages: javascript
  build_container:
    runs-on: ubuntu-latest
    steps:
      - name: Build Container
        run: |
          echo 'Building Docker container...'
          docker build -t myapp .
  job-2:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        uses: actions/checkout@v5
        with:
          ref: develop
    name: Job 2
    needs:
      - build