#test workflow
name: test workflow

on:
  workflow_dispatch: null
  push:
    branches:
      - main
      - develop
      - feat/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2