name: MER1 Pipeline
'on':
  workflow_dispatch: null
  push:
    paths-ignore:
      - .github/workflows/**
      - renovate.json
      - README.md
    branches:
      - main
      - develop
      - feat/**
jobs:
  call-am-generic-build:
    uses: turbo5000c/am-reuseable-workflow/.github/workflows/am-generic-build2.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}